language: elixir
sudo: false
script:
  - if [[ $(elixir --version) =~ "1.(8|9|10)." ]]; then mix format --check-formatted; fi
  - mix test
matrix:
  include:
    - elixir: "1.7.4"
      otp_release: "21.3.8.16"
    - elixir: "1.7.4"
      otp_release: "22.3.4.2"
    - elixir: "1.8.2"
      otp_release: "21.3.8.16"
    - elixir: "1.8.2"
      otp_release: "22.3.4.2"
    - elixir: "1.9.4"
      otp_release: "21.3.8.16"
    - elixir: "1.9.4"
      otp_release: "22.3.4.2"
    - elixir: "1.10.3"
      otp_release: "21.3.8.16"
    - elixir: "1.10.3"
      otp_release: "23.0.2"
